### ISSUE TITLE
Mpris script not working

### ISSUE THREAD

**Issue by antonagre** [jaseg/python-mpv#152]
If I try to start python-mpv client with the mpv-mpris script attached it will load normally but the mpris integration dosen't work.

I loaded the mpv wrapper
` mpv=MPV(video=False,scripts="/home/antonio/.config/mpv/scripts/mpris.so") `

and it give me no errors, but if I search avaiables mpris player I can't find it.

**Comment by jaseg** [comment]
I have a suspicion that you're having the same issue as #137. In #137, the issue was that mpris uses deprecated mpv API that has been removed from mpv a while ago.

In case the mpris plugin you're using is [this one](https://github.com/hoyon/mpv-mpris) it's likely to have that issue as their mpris.c still includes the old API.

Please try running python-mpv with something like ```log_handler=print, loglevel='debug'``` and see whether that yields any useful information. If you need more help, please re-open this issue with information on what mpris.so you are using, the output of mpv --version and what libmpv version you are using.

Have a nice day!
