### ISSUE TITLE
possible typo

### ISSUE THREAD

**Issue by eregni** [jaseg/python-mpv#166]
When I call the _wait_until_playing_ or _wait_until_paused_ method from an MPV instance I get a TypeError.
These two methods call _self.wait_for_property('core-idle')_
I believe the attribute _core-idle_ should be _core_idle_?
-> mpv.py line 906 and 917

**Comment by neinseg** [comment]
Thank you for the report.

No, the property is called "core-idle" in libmpv. libmpv uses dashes for all property names. When observing a property through the observer API the name is directly passed through to libmpv. The underscore variants of property names are only used for accessing properties through the MPV object's attributes, since python attribute names cannot contain dashes.

Could you please post a stack trace from the error that you get and post your libmpv version? If you have trouble figuring out your libmpv version you can read it from python like this: ```python3 -c 'import mpv; print(mpv.MPV().mpv_version)'```.
