### ISSUE TITLE
LibMPV Download?

### ISSUE THREAD

**Issue by prayag17** [jaseg/python-mpv#204]
How do I get libmpv files for all os? I tried getting .dll for windows from https://sourceforge.net/projects/mpv-player-windows/files/libmpv/ but the zip doesn't contain mpv-1.dll and I am unable to find one for Linux and MAC OS and M1 Mac

**Comment by jaseg** [comment]
The linked sourceforge page contains nightly builds of the development version of libmpv. Since the upcoming mpv version 0.35.0 will drop several APIs, it will use API version 2 (`mpv-2.dll`). However, this repo is still meant to be used with libmpv <= v0.34.1 (the latest release), which still uses API version 1 (`mpv-1.dll`). Please download an older libmpv version, and you will find `mpv-1.dll`.

**Comment by prayag17** [comment]
thanks, but how do I get libmpv files for MACOS and Linux?

**Comment by jaseg** [comment]
I think for neither of these you can find pre-built libmpv binaries that will be useful.

On MacOS I think the normal way to install mpv would be to use Homebrew, which you can't really ship with your app. Otherwise, you'd have to build mpv and all of its dependencies yourself. On Linux, your users should install libmpv from their distro package repository. If you just ship libmpv, it will likely not work, since it won't match the dependency  libs the user has already installed (like e.g. ffmpeg). If you want to provide your own libmpv build on linux, the only clean way of doing that would be to provide your app in a container format like appimage or flatpak ([flatpak mpv example here](https://github.com/flathub/flathub/pull/1057/files)).

**Comment by prayag17** [comment]
Ohk thanks
