### ISSUE TITLE
Two pypi Entries?

### ISSUE THREAD

**Issue by seandenigris** [jaseg/python-mpv#232]
There are:
- https://pypi.org/project/mpv/ and
- https://github.com/jaseg/python-mpv

Both point to this project. Why? I accidentally depended on the first and it caused quite a bit of grief (half a day googling obscure errors until I realized and loaded the other)

**Comment by jaseg** [comment]
The first one is not under my control. Someone else made this. The second one is the actual pypi entry of this project.

I know that the owner of the first entry is open to transferring it to me, I just have to write a few emails and coordinate with them to make that happen.

**Comment by seandenigris** [comment]
Thanks for the explanation :)

**Comment by baldurmen** [comment]
FWIW, you can request a namespace transfer via https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer

**Comment by jaseg** [comment]
I have contacted the old owner, and they have transferred the project. Since it's uncommon for python packages to have a "python-" prefix on their PyPI project name, I'm going to transfer the project to the "mpv" project on PyPI. I'm still going to keep the old project name alive for the forseeable future, since I expect a lot of stuff to depend on it. I will push new releases to both PyPI projects, but at some point I'm going to put a depreciation warning pointing at the mpv project into the releases under the python-mpv project.
