### ISSUE TITLE
[QUESTION] How do I add custom scripts?

### ISSUE THREAD

**Issue by TheCheddarCheese** [jaseg/python-mpv#276]
I installed a SponsorBlock script normally and it works when I open MPV though the app menu, but not with Python. How can I make it run in the module too?

**Comment by dfaker** [comment]
there's

`player.command('load-script','scriptname.lua')`

**Comment by jaseg** [comment]
Note that because python-mpv uses libmpv, it by default does not load the mpv configuration that you have in your home directory. This means any settings, key bindings or user scripts that you have installed for the `mpv` command-line interface will not be loaded by default by python-mpv.

You can however explicitly tell python-mpv to load the same user configuration that the regular `mpv` command-line utility loads by passing `config=True` to the `mpv.MPV` constructor like `mpv.MPV(.., config=True, ...)`. See [this issue](https://github.com/jaseg/python-mpv/issues/259) and [this comment from the libmpv documentation](https://github.com/mpv-player/mpv/blob/b68c742b271f6e36d9aedd9fa906a692d267dcd2/libmpv/client.h#L442) for details.
