### ISSUE TITLE
Issue with libmpv.so.1

### ISSUE THREAD

**Issue by twiffy** [jaseg/python-mpv#32]
Just from importing mpv, I'm getting this error:

> AttributeError: /usr/lib/arm-linux-gnueabihf/libmpv.so.1: undefined symbol: mpv_create_client

I'm a bit of a noob, so could easily be my fault or the system. Some possibly-relevant details:
1) On a raspberry pi 3. Manually installed python3.6, which seems to be working fine.
2) Installed libmpv via "sudo apt-get install libmpv-dev".
3) Installed mpv. Command "mpv myfile.mp3" works fine.

**Comment by jaseg** [comment]
That sounds very strange. Would you mind emailing me your ```libmpv.so```? It should be in that same folder.

**Comment by jaseg** [comment]
Also, can you post the output of ```mpv --version```, ```apt show mpv``` and ```apt show libmpv-dev```, please?

**Comment by McSinyx** [comment]
Notreally related but Stretch will be released on 2017-06-17 and have Python 3.5. I'm not sure how long it will take to Raspbian team to make RPi -specific image though.

**Comment by McSinyx** [comment]
@jaseg [Jessie has mpv and libmpv 0.6.2-2 while Stretch has 0.23.2-2](https://packages.debian.org/search?keywords=mpv&searchon=names&suite=all&section=all).

**Comment by jaseg** [comment]
That's exactly what I'm afraid of. They're probably running an antique version of ```libmpv```, and in that case there's really only the choice between upgrading the ```libmpv``` version to something sane or digging up a prehistoric ```python-mpv``` version. I mean, *0.6.2*, come on! There's nothing stable about that!

**Comment by jaseg** [comment]
Sorry for not getting back to your earlier, this issue just flew under my radar. In case you still are interested: Your system is running libmpv 0.6.2 while the current python-mpv release 0.2.5 is meant to be run against libmpv 0.22.0 . With libmpv, these version numbers are no joke as the API changes quite rapidly and profundly.

I think from this point you have two possible courses of action. One is to try using a *really* old python-mpv module. There might be one working with libmpv 0.6.2 somewhere deep in this repository's history.  The other is getting your libmpv up to date, but that would probably require using a different debian release (testing or sid instead of stable) since libmpv heavily depends on a large amount of other recent (mostly multimedia) library versions such as ffmpeg less than like, a year old, which you'll just not get on debian stable.

I'm sorry if that's not of much use to you, but I don't think there is much else that I can do on my end without investing a lot of time tracking not one but several moving targets (legacy libmpv versions). If there's anything unclear, please just comment or reopen this issue.

**Comment by McSinyx** [comment]
> the current python-mpv release 0.2.5 is meant to be run against libmpv 0.22

Is there anyway to perform libmpv version checking in the module or we have to tell to users to do so maually?

> The other is getting your libmpv up to date, but that would probably require using a different debian release (testing or sid instead of stable)

Debian 9 have just been released recently with libmpv 0.2.23, but I'm not sure if Raspbian 9 is out yet.

**Comment by jaseg** [comment]
> Is there anyway to perform libmpv version checking in the module or we have to tell to users to do so maually?

There is a function for that. The problem would be that in order to not complain about perfectly working versions, someone would have to check every python-mpv release against a whole bunch of mpv releases to set the minimum required version. That's just a lot of work.

Generally, older/newer versions will work *mostly* without problems. The most frequent change is that some properties are added or removed or change type and that won't be a problem if you don't use them. Because of that don't think it would really be a good idea to barf on "incompatible" libmpv versions as for many users that just wouldn't be a problem.
