### ISSUE TITLE
multiple external-file not supported?

### ISSUE THREAD

**Issue by za4410** [jaseg/python-mpv#34]
While we can pass multiple external-file arguments to the mpv itself like this:

mpv 1.mov --external-file=2.mov --external-file=3.mov --lavfi-complex="[vid1][vid2][vid3]..."

There is no visible way to do it with this app. I also tried the following:

player["external-file"] = ["2.mov","3.mov"]

which does not throw an error, but won't take the inputs either.

**Comment by jaseg** [comment]
This is interesting! I did not even know it could do that :D

This actually was not possible before since there was no support for setting node-typed options, which would be required to set any option to a list of file names. I pushed a fix to master. Please try it and tell me what you think. If it works fine I'll code up a few tests and publish a new version on pypi.

**Comment by za4410** [comment]
Beautiful! works great! Thanks!

**Comment by jaseg** [comment]
Awesome. I have pushed version 0.2.4 adding this change to [pypi](https://pypi.python.org/pypi/python-mpv).

**Comment by McSinyx** [comment]
The version on Github and PyPI are mismatched:

* diff `mpv.py`:
    ```diff
    49c49
    <     backend = CDLL('/home/user/mpv/build/libmpv.so')
    ---
    >     backend = CDLL(sofile) #'/home/user/mpv/build/libmpv.so')
    ```
  This causes import failure:
    ```python
    >>> import mpv
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/cnx/.local/lib/python3.5/site-packages/mpv.py", line 49, in <module>
        backend = CDLL('/home/user/mpv/build/libmpv.so')
      File "/usr/lib/python3.5/ctypes/__init__.py", line 351, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/user/mpv/build/libmpv.so: cannot open shared object file: No such file or directory
    ```

* diff `setup.py`:
    ```diff
    6c6
    <     version = '0.2.4',
    ---
    >     version = '0.2.3',
    ```

BTW about the `setup.py`, I suggest to use `distutils` because there isn't any `setuptools`'s feature used (and `setuptools` is a 3rd party library, so user have to install it to run `./setup.py install`). Also `setuptools.find_packages` is not used and the parenthesis in line 8 are meaningless. As you already used your real name in `mpv.py` copyright info, can you change line 10? And there is a space before closing square bracket in line 28 (column 50).

**Comment by jaseg** [comment]
Argh! Yes, I'm an idiot and accidentially pushed test code to pypi -.- Well, there is a 0.2.5 now up there with that fuckup corrected.

Thanks for the comments wrt. setup.py. I have pushed a fixed setup.py to master.

I'm using my legal name only in the copyright notices since that's legal stuff, but generally everyone only knows me by my alias so I'd like to keep that in the setup.py's author field.

As for setuptools vs. distutils, [the doc](https://docs.python.org/3/distributing/index.html#distributing-index) and [this guide](https://packaging.python.org/guides/tool-recommendations/#packaging-tool-recommendations) say the latter is not supposed to be used directly anymore and everybody has setuptools anyway so I'd rather lean towards setuptools here.

I don't see much of a point of using wheel in addition to setuptools, but if there is a way to publish wheels while maintaining backwards compatibility for people not using wheel I'd be fine with using that. I'll have a closer look into that.

**Comment by McSinyx** [comment]
As you decided to keep setuptools, I suggest to add Python version checker (e.g. python_requires='>=3.5') to prevent users from accidentally installing library. Also could you join line 13 and 14, because you once said you'll keep hard wrapping on column 120?
