### ISSUE TITLE
_get_property marked as private

### ISSUE THREAD

**Issue by za4410** [jaseg/python-mpv#37]
Is there any reason why "_get_property" function is marked as private (underscored)? I need to be able to request player's current playback time without "observing" it, and the only way I can do that now is by: 
player._get_property("playback-time")

where it really should be:
player.get_property("playback-time")

**Comment by jaseg** [comment]
Try ```player.playback_time```

**Comment by jaseg** [comment]
All mpv properties are mapped to attibutes on the ```MPV``` python object. Any dashes in the property name are replaced by underscores.

The accessor functions are autogenerated from a long list of all properties since they are all the same anyway and the exposed properties are constantly shifting.

The only instance where you'd need to use ```_get_property``` is if you'd want to access a ```libmpv``` property that didn't exist in the ```libmpv``` version this module was written against. There is a unit test checking congruency between what this module exposes and what ```libmpv``` exposes.

**Comment by jaseg** [comment]
Is this issue resolved for you? If it is not, please just re-open it.
