### ISSUE TITLE
Cannot use bound methods with register_key_binding

### ISSUE THREAD

**Issue by ssokolow** [jaseg/python-mpv#46]
`register_key_binding` dies with a somewhat confusing error when you attempt to use a bound method as a handler, as is commonplace in frameworks like PyGTK.

It'd probably be a good idea to document that so less experienced users don't get stuck.

This is the workaround I used:
```python
# pylint: disable=unnecessary-lambda
self.mpv.register_key_binding('q', lambda x, y: self.cb_quit(x, y))
```

**Comment by jaseg** [comment]
Thank you for the report. This should be fixed in master and v0.3.3 on pypi. You can now register key bindings with bound methods as you please. The two convenience attributes that were preventing this are now only set if you use the function decorator to register a binding. Also, this part has gotten some basic unit tests that already yielded one bug with unregistering key bindings.
