### ISSUE TITLE
app won't close pressing title bar close button

### ISSUE THREAD

**Issue by stax76** [jaseg/python-mpv#48]
In Windows 10 how can I make the app close when the close button of the title bar is pressed? 

```python
import sys, mpv

player = mpv.MPV(config='yes')

if len(sys.argv) == 1:
    sys.argv = ["",
               r"D:\Temp\StaxRip\doku.mkv",
               r"D:\Temp\StaxRip\Eli.mp4",
               r"D:\Temp\StaxRip\atmos.mkv"]

for file in sys.argv[1:]:
    player.playlist_append(file)

player.playlist_pos = 0

while True:
    player.wait_for_playback()
```

**Comment by jaseg** [comment]
That is [part of the default input bindings](https://github.com/mpv-player/mpv/blob/45bd739796f2dc2ecb2f67bb71120b1d1b3e1d44/etc/input.conf#L141). You could either load the default bindings by setting ```input_default_bindings=True``` in the constructor or manually add this one particular binding.

**Comment by stax76** [comment]
Neither works, I have input-default-bindings=yes in my mpv.conf
```
import sys, mpv

player = mpv.MPV(config='yes', input_default_bindings=True)

# to have the libmpv instance "quit", but not the python interpreter
player.register_key_binding("CLOSE_WIN", "quit")
# to manually orchestrate quitting from the python side
def quit(state, key):
    if state[0] == 'd':
        player.terminate()
        sys.exit(0)
player.register_key_binding("CLOSE_WIN", quit)

if len(sys.argv) == 1:
    sys.argv = ["",
               r"D:\Temp\StaxRip\doku.mkv",
               r"D:\Temp\StaxRip\Eli.mp4",
               r"D:\Temp\StaxRip\atmos.mkv"]

for file in sys.argv[1:]:
    player.playlist_append(file)

player.playlist_pos = 0

while True:
    player.wait_for_playback()
```

**Comment by jaseg** [comment]
So, there are a couple of problems here. First, be careful: if you register the same key binding twice, the second one will override the first one. So in the above example, only the second registration is effective. Doc [here](https://github.com/jaseg/python-mpv/blob/master/mpv.py#L948).

The function does not work due to a change in the upstream API since I wrote the doc (```'d'``` → ```'p'```). Besides fixing that I added a new ```MPV.on_key_press``` function decorator simplifying key bindings to python functions. This will be released as soon as I get libmpv to stop segfaulting on me.

The simple ```quit``` input command binding does not work because you are calling ```wait_for_playback``` in an infinite loop. That is, your player core will quit (which stops playback), but you will continue waiting for playback to finish (which will never happen). Meanwhile, the player window is still open since that one is kept open due to the libmpv config we're using here and will only close after you call ```player.terminate()```.

Here's some code that seems to work for me:
```python
#!/usr/bin/env python3
import mpv
import time

player = mpv.MPV(config='yes', input_default_bindings=True)

@player.on_key_press('CLOSE_WIN')
def quit():
    player.terminate()

player.play('LGR Plays - Goat Simulator-j4HY_fxwiZo.mp4')
player.wait_for_playback()
while True:
    # For demonstration purposes, do something else instead of terminating the python process.
    time.sleep(1)
```

Another variant would be the following. Note the place where ```player.terminate()``` is called.
```python
#!/usr/bin/env python3
import mpv
import time

player = mpv.MPV(config='yes', input_default_bindings=True)

player.register_key_binding('CLOSE_WIN', 'quit')

player.play('LGR Plays - Goat Simulator-j4HY_fxwiZo.mp4')
player.wait_for_playback()
player.terminate()
while True:
    # For demonstration purposes, do something else instead of terminating the python process.
    time.sleep(1)
```

**Comment by stax76** [comment]
I was evaluating all options and will much likely settle for C# because I have 15 years VB.NET experience and made a lot progress in my prototype. For every project I do I try to use a different language, with Python I'm a total n00b but I like the syntax a lot so I'll definitively look forward to learn and use it in the future.

Danke für die Hilfe
