### ISSUE TITLE
Does not support Windows

### ISSUE THREAD

**Issue by Evolution0** [jaseg/python-mpv#57]
Contrary to its PyPI classifiers python-mpv does not support Windows due to its usage of unix sockets. 

Windows *can* be supported however with the usage of a named pipe via pypiwin32. [Apps such as web3 support both this way](https://github.com/pipermerriam/web3.py/blob/master/web3/providers/ipc.py).

Tried implementing it myself but hit a stumbling block when trying to understand `JSONBaseProvider` used in the aforementioned app.

**Comment by jaseg** [comment]
Uff, thanks for the heads up. Since I'm no regular on Windows I'll just remove the classifier for now. Actually I wasn't even aware that this package is using unix domain sockets.

In any case before I re-add windows to the list of supported platforms I think I should really get a stable test setup working. Only testing stuff on linux and hoping nothing broke on Windows isn't the way to go, I think.
