### ISSUE TITLE
Property observer doesn't seem to receive correct values

### ISSUE THREAD

**Issue by maxosprojects** [jaseg/python-mpv#62]
Hi,

I'm running python-mpv 0.3.7 with mpv-1.dll x32 with Python 3.5.1 x32 on Windows 10 x64

The following snippet returns strange values:

```python
import mpv

player = mpv.MPV(ytdl=True)
player['vid'] = 'no'

@player.property_observer('time-pos')
def time_observer(_name, value):
  # Here, _value is either None if nothing is playing or a float containing
  # fractional seconds since the beginning of the file.
  # print('Now playing at {:.2f}s'.format(value))
  print('Now playing at ', str(value))

player.play('https://youtube.com/watch?v=vveaDYzgYxo')
player.wait_for_playback()
```

The output is:

```
Now playing at  1.3993628587e-314
Now playing at  1.5300098963e-314
Now playing at  1.2789014024e-314
Now playing at  1.3351258016e-314
Now playing at  4.91624003e-316
Now playing at  2.097007171e-314
Now playing at  1.2340848504e-314
Now playing at  4.84697793e-315
Now playing at  8.445882796e-315
Now playing at  1.8048847433e-314
Now playing at  1.636483184e-315
Now playing at  1.0954251585e-314
Now playing at  8.54366437e-315
Now playing at  1.5329976654e-314
Now playing at  6.927552357e-315
Now playing at  8.406498545e-315
Now playing at  1.646125505e-314
Now playing at  4.823890614e-315
Now playing at  1.1314142064e-314
Now playing at  1.1655019465e-314
Now playing at  5.52737466e-315
```

The formatted version that is commented out (from the example in README) prints `0.00s`, which is expected with the values above.

According to the docs that is supposed to be seconds.
Tried to listen on 'volume' - same result.

Am I missing something obvious here?

**Comment by McSinyx** [comment]
Since you're using 32-bit mpv and Python, this could be an duplicate of #50: https://github.com/jaseg/python-mpv/issues/50#issuecomment-327491253

**Comment by maxosprojects** [comment]
So it is obvious, like existing issue. Sorry about that.

Any plans on fixing that? Or at least merging #54 for the time being? It does solve the problem.

**Comment by McSinyx** [comment]
If you read the comments on #50, you can see @jaseg is working on this. Maybe the #54 hack is a bit ugly, or he wanna push himself harder by not accepting any temporary fix (?). He haven't answered to related problem since then but I'm afraid to ask because I know pushing doesn't really help solving it any faster.

BTW I'm glad that 4d620aed441a1de5bb2b92adce326a20ec386899 works for you.

**Comment by jaseg** [comment]
Yes, sorry for the delay on #50. Problem with that one IIRC was that it fixed the type confusion with another type confusion that just happened to work by chance. I'll probably have some downtime the next couple of days so I'll try to look into that.

**Comment by McSinyx** [comment]
Thanks a lot. Off-topic: Don't spent your entire vacation on this; and also, how could you manage your life so beautifully? Work, life, hobbies (195 repos on Github)? I just want tips to be like you in the future. I'm still a student now.

**Comment by jaseg** [comment]
Heh, don't worry, I'm fine. But thanks you for your concern 😸

btw, I'm also still studying. The large number of repos is really just me dumping most of what I'm doing code-wise on github since like forever. I don't think I have any specific advice apart from, do what you find interesting and keep doing it.
