### ISSUE TITLE
Can't import mpv with Python 3.6.8

### ISSUE THREAD

**Issue by TimeTraveller-San** [jaseg/python-mpv#80]
When I import mpv I get the following error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timetraveller/.local/lib/python3.6/site-packages/mpv.py", line 11, in <module>
    backend = CDLL('libmpv.so')
  File "/home/timetraveller/miniconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var
```
mpv version:
``` mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1
```

**Comment by jaseg** [comment]
harfbuzz is a typesetting library. I'm 98% sure your issue is being caused by some out-of-date build linked against old dependencies. Try running a full system update on your machine and make sure all packages are in their most recent version. If you built anything like harfbuzz or libmpv yourself, rebuild and re-install it after the update to make sure everything is linked to up-to-date dependencies.

**Comment by TimeTraveller-San** [comment]
I recently did a `pacman -Syyu` and also updated all my python packages. 
pacman probably broke something again, like always. I will look into it. Closing the issue.
